
#ifndef _MLV_GAME_STRATEGY_H
#define _MLV_GAME_STRATEGY_H

#define GAME_WINDOW_WIDTCH 360
#define GAME_WINDOW_HEIGHT 540

#define GAME_PADDING GAME_WINDOW_WIDTCH / 10
#define GRID_VERTICAL_POS GAME_PADDING * 2
#define GRID_HEIGHT GAME_WINDOW_HEIGHT * 6 / 10

#define CELL_SIZE ( GAME_WINDOW_WIDTCH - GAME_PADDING * 2 ) / 9

#define MAX_SCORE_TEXT_SIZE 10

#include"mlv_game_screen.h"


#endif /* _MLV_GAME_STRATEGY_H  */